[package]
name = "qca-sim"
version = "0.1.0"
edition = "2021"

[profile.profiling]
inherits = "release"
debug = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
qca-core = {path = "../qca-core"}
serde_json = "1.0.117"