name: BuildTestDeploy

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  Build:
    strategy:
      matrix:
        os: [windows-latest, linux-latest]

    runs-on: ${{ matrix.os }}

    steps:

    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Configure/Generate
      run: >-
        cmake
        -Bbuild   

    - name: Build
      run: >- 
        cmake 
        --build build 
        --parallel 
        -DCHERRY_ENABLE_IMGUI=TRUE