name: Build and Test

on:
  [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        config: [debug, release]
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: windows-latest
            artifact_suffix: .exe
          - os: ubuntu-latest
            artifact_suffix: ""
          - os: macos-latest
            artifact_suffix: ""
    steps:
    - uses: actions/checkout@v4
    
    - name: Build
      if: matrix.config == 'debug'
      run: cargo build --verbose
    
    - name: Build
      if: matrix.config == 'release'
      run: cargo build --verbose --release
    
    - name: Run tests
      run: cargo test --verbose
      if: matrix.config == 'debug'

    - name: Run tests
      run: cargo test --verbose --release
      if: matrix.config == 'release'
      
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts-${{ matrix.os }}-${{ matrix.config }}
        path: target/${{ matrix.config }}/qca-sim${{ matrix.artifact_suffix }}
        retention-days: 1