name: Release

on:
    push:
        tags:
            - 'v*'
    workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build and Upload Artifacts
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: windows-latest
            artifact_suffix: .exe
          - os: ubuntu-latest
            artifact_suffix: ""
          - os: macos-latest
            artifact_suffix: ""
    steps:
    - uses: actions/checkout@v4
    
    - name: Build
      run: cargo build --verbose --release
      
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: qca-sim-${{ github.ref_name }}-${{ matrix.os }}
        path: target/release/qca-sim${{ matrix.artifact_suffix }}
        retention-days: 1

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Rename executables with platform info
        run: |
          mkdir -p release-files
          cp artifacts/qca-sim-*-ubuntu-latest/qca-sim release-files/qca-sim-${{ github.ref_name }}-linux
          cp artifacts/qca-sim-*-windows-latest/qca-sim.exe release-files/qca-sim-${{ github.ref_name }}-windows.exe
          cp artifacts/qca-sim-*-macos-latest/qca-sim release-files/qca-sim-${{ github.ref_name }}-macos

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          name: QCASim ${{ github.ref_name }}
          files: |
            release-files/*
        
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}